export const LOGIN = {
    INVALID_USERNAME_PASSWORD: 1,
    LOGIN_FAILED: 0,
};

export const GET_ME = {
    USER_NOT_FOUND: 1,
    ROLES_NOT_FOUND: 2,
    PERMISSIONS_NOT_FOUND: 3,
    GET_ME_FAILED: 0,
};

export const REFRESH_TOKEN = {
    INVALID_TOKEN: 1,
    TOKEN_NOT_FOUND: 2,
    ACCOUNT_NOT_FOUND: 3,
    REFRESH_TOKEN_FAILED: 0,
};

export const LOGOUT = {
    LOGOUT_SUCCESS: 1,
    LOGOUT_FAILED: 0,
};

export const LOGOUT_ALL = {
    LOGOUT_ALL_SUCCESS: 1,
    LOGOUT_ALL_FAILED: 0,
};

export const RESET_PASSWORD = {
    INVALID_RESET_PASSWORD_TOKEN: 1,
    NEW_PASSWORD_CONFIRM_PASSWORD_NOT_MATCH: 2,
    ACCOUNT_NOT_FOUND: 3,
    RESET_PASSWORD_SUCCESS: 4,
    RESET_PASSWORD_FAILED: 0,
};
